on:
  registry_package:
    action: [published]
  watch:
    types: [started]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - run: echo A package was published!

    - name: Dump GitHub context
      env:
        GITHUB_CONTEXT: ${{ toJson(github) }}
      run: echo "$GITHUB_CONTEXT"
