on:
  registry_package:
    name: registry-package-eventx    
  watch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - run: echo A package was published!

    - name: Dump GitHub context
      env:
        GITHUB_CONTEXT: ${{ toJson(github) }}
      run: echo "$GITHUB_CONTEXT"
